version: '3.8'

services:
  # auth-service:
  #   build:
  #     context: ./auth-service
  #     dockerfile: Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   volumes:
  #     - ./auth-service/db.sqlite:/tmp/db.sqlite

  game-service:
    build:
      context: ./game-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      # - auth-service
      - game-service
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
